export enum actionType {
  DISPLAY_ALERT = 'DISPLAY_ALERT',
  FORM_INPUT = 'FORM_INPUT',
  REMOVE_ALL = 'REMOVE_ALL',
  ADD_ITEM = 'ADD_ITEM',
  EDIT_ITEM = 'EDIT_ITEM',
  EDITING_ITEM = 'EDITING_ITEM',
  TOOGLE_COMPLETE = 'TOOGLE_COMPLETE',
  DELETE_ITEM = 'DELETE_ITEM',
}
